---
- name: "Update loadbalancer config in '{{ test_dir | default('') }}{{ haproxy_config['path'] }}'"
  ansible.builtin.template:
    dest: "{{ test_dir | default('') }}{{ haproxy_config['path'] }}"
    src: haproxy.ji2
    backup: true
    validate: haproxy -c -f %s
  notify: "Restart haproxy service"
