---
- name: "Update loadbalancer config in {{ haproxy_config['file'] }}"
  ansible.builtin.template:
    dest: "{{ haproxy_config['file'] }}"
    src: haproxy.ji2
    backup: true
  notify: "Restart service"
