- name: "Enable haproxy_connect_any SELinux property"
  tags: selinux-sebool
  ansible.posix.seboolean:
    name: haproxy_connect_any
    state: yes
    persistent: yes

- name: "Allow ports in SELinux"
  tags: selinux-seport
  community.general.seport:
    ports: "{{ item | string }}"
    proto: tcp
    setype: http_port_t
  loop: "{{ haproxy_firewalld['zones'] | map(attribute='ports') | flatten | unique }}"
